document.write( '<header>\n' );
document.write( '            <span class=\"menu-trigger\"><img src=\"img/menu.png\" alt=\"\"></span>\n' );
document.write( '            <nav class=\"mobile-only\">\n' );
document.write( '                <span class=\"menu-close\" ><img src=\"img/back.png\" alt=\"\"></span>\n' );
document.write( '                <ul class=\"navbar-nav justify-content-center\">\n' );
document.write( '                    <li class=\"nav-item\">\n' );
document.write( '                        <a class=\"nav-link\" href=\"index.html\"><img src=\"img/icons/whitefavicon32.png\"></a>\n' );
document.write( '                    </li>\n' );
document.write( '\n' );
document.write( '                    <li class=\"nav-item\">\n' );
document.write( '                        <a class=\"nav-link\" href=\"index.html\">Get Started</a>\n' );
document.write( '                        <ul class=\"submenuitem\">\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/wallet.png\" alt=\"\"></span><a href=\"#wallets_dropdown\"><font color=\"black\">Downloading Wallet</font></a></li>\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/purchasing.png\" alt=\"\"></span><a href=\"#purchasing_dropdown\"><font color=\"black\">Purchasing Peercoin</font></a></li>\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/anvil_black.png\" alt=\"\"></span><a href=\"#minting_dropdown\"><font color=\"black\">Minting Peercoin</font></a></li>\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/pickaxe_black.png\" alt=\"\"></span><a href=\"#mining_dropdown\"><font color=\"black\">Mining Peercoin</font></a></li>\n' );
document.write( '                        </ul>\n' );
document.write( '                    </li>\n' );
document.write( '                    <li class=\"nav-item\">\n' );
document.write( '                        <a class=\"nav-link\" href=\"#\">Learn</a>\n' );
document.write( '                        <ul class=\"submenuitem\">\n' );
document.write( '                            <div class=\"article-heading row\">\n' );
document.write( '                                    <div class=\"icon col-2\"><img src=\"img/logos/webfixed/circlefavicon64.png\" alt=\"\"></div>\n' );
document.write( '                                    <div class=\"col-10\">\n' );
document.write( '                                        <h4>Peercoin University</h4>\n' );
document.write( '                                        <p>Lorem ipsum dolor sit sicing elit.</p>\n' );
document.write( '                                    </div>\n' );
document.write( '                            </div>\n' );
document.write( '                            <div class=\"row\">\n' );
document.write( '                                <li class=\"col-4\"><a href=\"#\">Introduction</a></li>\n' );
document.write( '                                    <li class=\"col-12\"><a href=\"#\">What is a Blockchain?</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">Benefits & Use Cases</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">When Decentralization Fails</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">Bitcoin & Proof-of-Work Consensus</a></li>\n' );
document.write( '\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">Centralization of Bitcoin</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">Bitcoin’s Lack of Sustainability</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">Bitcoin’s Lack of Scalability</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">Peercoin & Proof-of-Stake Consensus</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">First Efficient & Sustainable Blockchain</a></li>\n' );
document.write( '\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">Economics of Peercoin</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">Scalability of Peercoin</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">A Stronger Foundation to Build Upon</a></li>\n' );
document.write( '                            </div>\n' );
document.write( '                            <div class=\"article-heading row\">\n' );
document.write( '                                <div class=\"icon col-2\"><img src=\"img/logos/webfixed/circlefavicon64.png\" alt=\"\"></div>\n' );
document.write( '                                <div class=\"col-10\">\n' );
document.write( '                                    <h4>Selected Articles</h4>\n' );
document.write( '                                    <p>Selected writings from the Peercoin Foundation.</p>\n' );
document.write( '                                </div>\n' );
document.write( '                            </div>\n' );
document.write( '                            <div class=\"row\">\n' );
document.write( '                                <li class=\"col-4\"><a href=\"https://medium.com/peercoin/deflation-and-cryptocurrencies-the-long-term-ramifications-of-fixed-supply-currencies-c192f44dddc1\">Deflation and Cryptocurrencies</a></li>\n' );
document.write( '                                <li class=\"col-4\"><a href=\"https://medium.com/peercoin/peercoins-hybrid-chain-solution-to-proof-of-work-global-scaling-and-environmental-impact-c36757e89d6e\">Peercoin\'s Hybrid Chain Solution</a></li>\n' );
document.write( '                                <li class=\"col-4\"><a href=\"https://medium.com/peercoin/the-rich-get-richer-concept-in-proof-of-stake-systems-82c5ceeff326\">Rich Get Richer Fallacy</a></li>\n' );
document.write( '                                <li class=\"col-4\"><a href=\"https://medium.com/peercoin/how-to-buy-peercoin-58b48ab58315\">How to Buy Peercoin</a></li>\n' );
document.write( '                                <li class=\"col-4\"><a href=\"https://docs.peercoin.net/#/how-to-sign-a-message-using-the-peercoin-client\">Signing a Message with the Peercoin Client</a></li>\n' );
document.write( '                                <li class=\"col-4\"><a href=\"https://docs.peercoin.net/#/frequently-asked-questions\">Frequently Asked Questions</a></li>\n' );
document.write( '                            </div>\n' );
document.write( '                        </ul>\n' );
document.write( '                    </li>\n' );
document.write( '                    <li class=\"nav-item\">\n' );
document.write( '                        <a class=\"nav-link\" href=\"resources.html\">Resources</a>\n' );
document.write( '                        <ul class=\"submenuitem\">\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/docs.png\" alt=\"\"></span><a href=\"https://docs.peercoin.net/\"><font color=\"black\">Documentation</font></a></li>\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/exchange.png\" alt=\"\"><a href=\"resources.html#exchanges\"><font color=\"black\">Exchanges</font></a></span></li>\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/block.png\" alt=\"\"></span><a href=\"resources.html#blockexplorers\"><font color=\"black\">Block Explorers</font></a></li>\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/whitepaper.png\" alt=\"\"></span><a href=\"resources.html#whitepaper\"><font color=\"black\">Whitepaper</font></a></li>\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/graphics.png\" alt=\"\"></span><a href=\"resources.html#graphics\"><font color=\"black\">Graphics</font></a></li>\n' );
document.write( '                        </ul>\n' );
document.write( '                    </li>\n' );
document.write( '                    <li class=\"nav-item\">\n' );
document.write( '                        <a class=\"nav-link\" href=\"#\">Wallets</a>\n' );
document.write( '                    </li>\n' );
document.write( '                    <li class=\"nav-item\">\n' );
document.write( '                        <a class=\"nav-link\" href=\"#\">Project</a>\n' );
document.write( '                        <ul class=\"submenuitem\">\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/roadmap.png\" alt=\"\"></span><a href=\"roadmap.html\"><font color=\"black\">Roadmap</font></a></li>\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/projects.png\" alt=\"\"></span><a href=\"projects.html\"><font color=\"black\">Projects</font></a></li>\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/blog.png\" alt=\"\"></span><a href=\"https://medium.com/peercoin\"><font color=\"black\">Blog</font></a></li>\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/foundation.png\" alt=\"\"></span><a href=\"foundation.html\"><font color=\"black\">Foundation</font></a></li>\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/contact.png\" alt=\"\"></span><a href=\"contactus.html\"><font color=\"black\">Contact Us</font></a></li>\n' );
document.write( '                        </ul>\n' );
document.write( '                    </li>\n' );
document.write( '                    <li class=\"nav-item\">\n' );
document.write( '                        <a class=\"nav-link\" href=\"resources.html#communities\">Community</a>\n' );
document.write( '                        <ul class=\"submenuitem\">\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/forum.png\" alt=\"\"></span><a href=\"https://talk.peercoin.net/\"><font color=\"black\">Forum</font></a></li>\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/twitter.png\" alt=\"\"></span><a href=\"https://twitter.com/PeercoinPPC\"><font color=\"black\">Twitter</font></a></li>\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/facebook.png\" alt=\"\"></span><a href=\"https://www.facebook.com/Peercoin/\"><font color=\"black\">Facebook</font></a></li>\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/reddit.png\" alt=\"\"></span><a href=\"https://www.reddit.com/r/peercoin\"><font color=\"black\">Reddit</font></a></li>\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/telegram.png\" alt=\"\"></span><a href=\"https://www.reddit.com/r/peercoin\"><font color=\"black\">Telegram</font></a></li>\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/discord.png\" alt=\"\"></span><a href=\"https://discord.gg/XPxfwtG\"><font color=\"black\">Discord</font></a></li>\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/youtube.png\" alt=\"\"></span><a href=\"https://www.youtube.com/user/PeerCoin\"><font color=\"black\">Youtube</font></a></li>\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/github.png\" alt=\"\"></span><a href=\"https://github.com/peercoin/\"><font color=\"black\">Github</font></a></li>\n' );
document.write( '                            <li><span class=\"icon\"><img src=\"img/icons/bitcoinchat.png\" alt=\"\"></span><a href=\"https://bitcointalk.org/index.php?topic=101820.0;topicseen\"><font color=\"black\">Bitcoin Talk</font></a></li>\n' );
document.write( '                        </ul>\n' );
document.write( '                    </li>\n' );
document.write( '                    <li id=\"language\" class=\"nav-item\">\n' );
document.write( '                        <a class=\"nav-link\" href=\"#\"><span>EN</span></a>\n' );
document.write( '                    </li>\n' );
document.write( '                </ul>\n' );
document.write( '            </nav>\n' );
document.write( '            <nav class=\"navbar navbar-expand-lg\">\n' );
document.write( '                <div class=\"collaspe navbar-collapse\" id=\"navbarNav\">\n' );
document.write( '                    <ul class=\"navbar-nav justify-content-center\">\n' );
document.write( '                        <li class=\"nav-item\">\n' );
document.write( '                                <a class=\"nav-link\" href=\"index.html\"><img src=\"img/icons/whitefavicon32.png\"></a>\n' );
document.write( '                        </li>\n' );
document.write( '                        <!-- Learn -->\n' );
document.write( '                        <li id=\"learn\" class=\"nav-item\">\n' );
document.write( '                            <a class=\"nav-link\" href=\"#\">Learn</a>\n' );
document.write( '                            <ul class=\"submenuitem\">\n' );
document.write( '                                <div class=\"article-heading row\">\n' );
document.write( '                                    <div class=\"icon col-2\"><img src=\"img/logos/webfixed/circlefavicon64.png\" alt=\"\"></div>\n' );
document.write( '                                    <div class=\"col-10\">\n' );
document.write( '                                        <h4>Peercoin University</h4>\n' );
document.write( '                                        <p>Lorem ipsum dolor sit sicing elit.</p>\n' );
document.write( '                                    </div>\n' );
document.write( '                                </div>\n' );
document.write( '                                <div class=\"row\">\n' );
document.write( '                                    <li class=\"col-6\"><a href=\"#\">Introduction</a></li>\n' );
document.write( '                                    <li class=\"col-6\"><a href=\"#\">What is a Blockchain?</a></li>\n' );
document.write( '                                    <li class=\"col-6\"><a href=\"#\">Benefits & Use Cases</a></li>\n' );
document.write( '                                    <li class=\"col-6\"><a href=\"#\">When Decentralization Fails</a></li>\n' );
document.write( '                                    <li class=\"col-6\"><a href=\"#\">Bitcoin & Proof-of-Work Consensus</a></li>\n' );
document.write( '\n' );
document.write( '                                    <li class=\"col-6\"><a href=\"#\">Centralization of Bitcoin</a></li>\n' );
document.write( '                                    <li class=\"col-6\"><a href=\"#\">Bitcoin’s Lack of Sustainability</a></li>\n' );
document.write( '                                    <li class=\"col-6\"><a href=\"#\">Bitcoin’s Lack of Scalability</a></li>\n' );
document.write( '                                    <li class=\"col-6\"><a href=\"#\">Peercoin & Proof-of-Stake Consensus</a></li>\n' );
document.write( '                                    <li class=\"col-6\"><a href=\"#\">First Efficient & Sustainable Blockchain</a></li>\n' );
document.write( '\n' );
document.write( '                                    <li class=\"col-6\"><a href=\"#\">Economics of Peercoin</a></li>\n' );
document.write( '                                    <li class=\"col-6\"><a href=\"#\">Scalability of Peercoin</a></li>\n' );
document.write( '                                    <li class=\"col-6\"><a href=\"#\">A Stronger Foundation to Build Upon</a></li>\n' );
document.write( '                                </div>\n' );
document.write( '                                <div class=\"article-heading row\">\n' );
document.write( '                                    <div class=\"icon col-2\"><img src=\"img/logos/webfixed/circlefavicon64.png\" alt=\"\"></div>\n' );
document.write( '                                    <div class=\"col-10\">\n' );
document.write( '                                        <h4>Selected Articles</h4>\n' );
document.write( '                                        <p>Selected writings from the Peercoin Foundation.</p>\n' );
document.write( '                                    </div>\n' );
document.write( '                                </div>\n' );
document.write( '                                <div class=\"row\">\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"https://medium.com/peercoin/deflation-and-cryptocurrencies-the-long-term-ramifications-of-fixed-supply-currencies-c192f44dddc1\">Deflation and Cryptocurrencies</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"https://medium.com/peercoin/peercoins-hybrid-chain-solution-to-proof-of-work-global-scaling-and-environmental-impact-c36757e89d6e\">Peercoin\'s Hybrid Chain Solution</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"https://medium.com/peercoin/the-rich-get-richer-concept-in-proof-of-stake-systems-82c5ceeff326\">Rich Get Richer Fallacy</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"https://medium.com/peercoin/how-to-buy-peercoin-58b48ab58315\">How to Buy Peercoin</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"https://docs.peercoin.net/#/how-to-sign-a-message-using-the-peercoin-client\">Signing a Message with the Peercoin Client</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"https://docs.peercoin.net/#/frequently-asked-questions\">Frequently Asked Questions</a></li>\n' );
document.write( '                                </div>\n' );
document.write( '                            </ul>\n' );
document.write( '                        </li>\n' );
document.write( '                        <!-- Get Started -->\n' );
document.write( '                        <li id=\"get-started\" class=\"nav-item\">\n' );
document.write( '                            <a class=\"nav-link\" href=\"index.html\">Get Started</a>\n' );
document.write( '                            <ul class=\"submenuitem\">\n' );
document.write( '                                <div class=\"row\">\n' );
document.write( '                                    <div class=\"col-12\">\n' );
document.write( '                                        <li><span class=\"icon\"><img src=\"img/icons/wallet.png\" alt=\"\"></span><a href=\"index.html#wallet_dropdown\"><font color=\"black\">Downloading Wallet</font></a></li>\n' );
document.write( '                                        <li><span class=\"icon\"><img src=\"img/icons/purchasing.png\" alt=\"\"></span><a href=\"#purchasing_dropdown\"><font color=\"black\">Purchasing Peercoin</font></a></li>\n' );
document.write( '                                        <li><span class=\"icon\"><img src=\"img/icons/anvil_black.png\" alt=\"\"></span><a href=\"#minting_dropdown\"><font color=\"black\">Minting Peercoin</font></a></li>\n' );
document.write( '                                        <li><span class=\"icon\"><img src=\"img/icons/pickaxe_black.png\" alt=\"\"></span><a href=\"#mining_dropdown\"><font color=\"black\">Mining Peercoin</font></a></li>\n' );
document.write( '                                    </div>\n' );
document.write( '                                </div>\n' );
document.write( '                            </ul>\n' );
document.write( '                        </li>\n' );
document.write( '                        <!-- Resources -->\n' );
document.write( '                        <li id=\"resources\" class=\"nav-item\">\n' );
document.write( '                            <a class=\"nav-link\" href=\"resources.html\">Resources</a>\n' );
document.write( '                            <ul class=\"submenuitem\">\n' );
document.write( '                                <li><span class=\"icon\"><img src=\"img/icons/docs.png\" alt=\"\"></span><a href=\"https://docs.peercoin.net/\"><font color=\"black\">Documentation</font></a></li>\n' );
document.write( '                                <li><span class=\"icon\"><img src=\"img/icons/exchange.png\" alt=\"\"><a href=\"resources.html#exchanges\"><font color=\"black\">Exchanges</font></a></span></li>\n' );
document.write( '                                <li><span class=\"icon\"><img src=\"img/icons/block.png\" alt=\"\"></span><a href=\"resources.html#blockexplorers\"><font color=\"black\">Block Explorers</font></a></li>\n' );
document.write( '                                <li><span class=\"icon\"><img src=\"img/icons/whitepaper.png\" alt=\"\"></span><a href=\"resources.html#whitepaper\"><font color=\"black\">Whitepaper</font></a></li>\n' );
document.write( '                                <li><span class=\"icon\"><img src=\"img/icons/graphics.png\" alt=\"\"></span><a href=\"resources.html#graphics\"><font color=\"black\">Graphics</font></a></li>\n' );
document.write( '                            </ul>\n' );
document.write( '                        </li>\n' );
document.write( '                        <!-- Projects -->\n' );
document.write( '                        <li id=\"projects\" class=\"nav-item\">\n' );
document.write( '                            <a class=\"nav-link\" href=\"#\">Project</a>\n' );
document.write( '                            <ul class=\"submenuitem\">\n' );
document.write( '                                <li><span class=\"icon\"><img src=\"img/icons/roadmap.png\" alt=\"\"></span><a href=\"roadmap.html\"><font color=\"black\">Roadmap</font></a></li>\n' );
document.write( '                                <li><span class=\"icon\"><img src=\"img/icons/projects.png\" alt=\"\"></span><a href=\"projects.html\"><font color=\"black\">Projects</font></a></li>\n' );
document.write( '                                <li><span class=\"icon\"><img src=\"img/icons/blog.png\" alt=\"\"></span><a href=\"https://medium.com/peercoin\"><font color=\"black\">Blog</font></a></li>\n' );
document.write( '                                <li><span class=\"icon\"><img src=\"img/icons/foundation.png\" alt=\"\"></span><a href=\"foundation.html\"><font color=\"black\">Foundation</font></a></li>\n' );
document.write( '                                <li><span class=\"icon\"><img src=\"img/icons/contact.png\" alt=\"\"></span><a href=\"contactus.html\"><font color=\"black\">Contact Us</font></a></li>\n' );
document.write( '                            </ul>\n' );
document.write( '                        </li>\n' );
document.write( '                         <!-- Wallet -->\n' );
document.write( '                        <li id=\"wallet\" class=\"nav-item\">\n' );
document.write( '                            <a class=\"nav-link\" href=\"wallet.html\">Wallet</a>\n' );
document.write( '                        </li>\n' );
document.write( '                         <!-- Community -->\n' );
document.write( '                        <li id=\"community\" class=\"nav-item\">\n' );
document.write( '                            <a class=\"nav-link\" href=\"resources.html#communities\">Community</a>\n' );
document.write( '                            <ul class=\"submenuitem\">\n' );
document.write( '                                <li><span class=\"icon\"><img src=\"img/icons/forum.png\" alt=\"\"></span><a href=\"https://talk.peercoin.net/\"><font color=\"black\">Forum</font></a></li>\n' );
document.write( '                                <li><span class=\"icon\"><img src=\"img/icons/twitter.png\" alt=\"\"></span><a href=\"https://twitter.com/PeercoinPPC\"><font color=\"black\">Twitter</font></a></li>\n' );
document.write( '                                <li><span class=\"icon\"><img src=\"img/icons/facebook.png\" alt=\"\"></span><a href=\"https://www.facebook.com/Peercoin/\"><font color=\"black\">Facebook</font></a></li>\n' );
document.write( '                                <li><span class=\"icon\"><img src=\"img/icons/reddit.png\" alt=\"\"></span><a href=\"https://www.reddit.com/r/peercoin\"><font color=\"black\">Reddit</font></a></li>\n' );
document.write( '                                <li><span class=\"icon\"><img src=\"img/icons/telegram.png\" alt=\"\"></span><a href=\"https://www.reddit.com/r/peercoin\"><font color=\"black\">Telegram</font></a></li>\n' );
document.write( '                                <li><span class=\"icon\"><img src=\"img/icons/discord.png\" alt=\"\"></span><a href=\"https://discord.gg/XPxfwtG\"><font color=\"black\">Discord</font></a></li>\n' );
document.write( '                                <li><span class=\"icon\"><img src=\"img/icons/youtube.png\" alt=\"\"></span><a href=\"https://www.youtube.com/user/PeerCoin\"><font color=\"black\">Youtube</font></a></li>\n' );
document.write( '                                <li><span class=\"icon\"><img src=\"img/icons/github.png\" alt=\"\"></span><a href=\"https://github.com/peercoin/\"><font color=\"black\">Github</font></a></li>\n' );
document.write( '                                <li><span class=\"icon\"><img src=\"img/icons/bitcoinchat.png\" alt=\"\"></span><a href=\"https://bitcointalk.org/index.php?topic=101820.0;topicseen\"><font color=\"black\">Bitcoin Talk</font></a></li>\n' );
document.write( '                            </ul>\n' );
document.write( '                        </li>\n' );
document.write( '                         <!-- Get Started -->\n' );
document.write( '                        <li id=\"language\" class=\"nav-item\">\n' );
document.write( '                            <a class=\"nav-link\" href=\"#\"><span>EN</span></a>\n' );
document.write( '                        </li>\n' );
document.write( '                    </ul>\n' );
document.write( '                </div>\n' );
document.write( '            </nav>\n' );
document.write( '            <nav class=\"navbar navbar-expand-lg stick\">\n' );
document.write( '                <div class=\"row\">\n' );
document.write( '                    <div class=\"col-sm-3\">\n' );
document.write( '                        <img src=\"img/logo.png\" alt=\"\" style=\"max-height: 40px;\">\n' );
document.write( '                    </div>\n' );
document.write( '                    <div class=\"col-sm-9\">\n' );
document.write( '                        <ul>\n' );
document.write( '                            <li id=\"learn\" class=\"nav-item\">\n' );
document.write( '                                <a class=\"nav-link\" href=\"#\">Learn</a>\n' );
document.write( '                                <ul class=\"submenuitem\">\n' );
document.write( '                                    <div class=\"article-heading row\">\n' );
document.write( '                                    <div class=\"icon col-2\"><img src=\"img/logos/webfixed/circlefavicon64.png\" alt=\"\"></div>\n' );
document.write( '                                    <div class=\"col-10\">\n' );
document.write( '                                        <h4>Peercoin University</h4>\n' );
document.write( '                                        <p>Lorem ipsum dolor sit sicing elit.</p>\n' );
document.write( '                                    </div>\n' );
document.write( '                                </div>\n' );
document.write( '                                <div class=\"row\">\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">Introduction</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">What is a Blockchain?</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">Benefits & Use Cases</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">When Decentralization Fails</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">Bitcoin & Proof-of-Work Consensus</a></li>\n' );
document.write( '\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">Centralization of Bitcoin</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">Bitcoin’s Lack of Sustainability</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">Bitcoin’s Lack of Scalability</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">Peercoin & Proof-of-Stake Consensus</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">First Efficient & Sustainable Blockchain</a></li>\n' );
document.write( '\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">Economics of Peercoin</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">Scalability of Peercoin</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"#\">A Stronger Foundation to Build Upon</a></li>\n' );
document.write( '                                </div>\n' );
document.write( '                                <div class=\"article-heading row\">\n' );
document.write( '                                    <div class=\"icon col-2\"><img src=\"img/logos/webfixed/circlefavicon64.png\" alt=\"\"></div>\n' );
document.write( '                                    <div class=\"col-10\">\n' );
document.write( '                                        <h4>Selected Articles</h4>\n' );
document.write( '                                        <p>Selected writings from the Peercoin Foundation.</p>\n' );
document.write( '                                    </div>\n' );
document.write( '                                </div>\n' );
document.write( '                                <div class=\"row\">\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"https://medium.com/peercoin/deflation-and-cryptocurrencies-the-long-term-ramifications-of-fixed-supply-currencies-c192f44dddc1\">Deflation and Cryptocurrencies</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"https://medium.com/peercoin/peercoins-hybrid-chain-solution-to-proof-of-work-global-scaling-and-environmental-impact-c36757e89d6e\">Peercoin\'s Hybrid Chain Solution</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"https://medium.com/peercoin/the-rich-get-richer-concept-in-proof-of-stake-systems-82c5ceeff326\">Rich Get Richer Fallacy</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"https://medium.com/peercoin/how-to-buy-peercoin-58b48ab58315\">How to Buy Peercoin</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"https://docs.peercoin.net/#/how-to-sign-a-message-using-the-peercoin-client\">Signing a Message with the Peercoin Client</a></li>\n' );
document.write( '                                    <li class=\"col-4\"><a href=\"https://docs.peercoin.net/#/frequently-asked-questions\">Frequently Asked Questions</a></li>\n' );
document.write( '                                </div>\n' );
document.write( '                                </ul>\n' );
document.write( '                            </li>\n' );
document.write( '                            <li id=\"get-started\" class=\"nav-item\">\n' );
document.write( '                                <a class=\"nav-link\" href=\"index.html\">Get Started</a>\n' );
document.write( '                                <ul class=\"submenuitem\">\n' );
document.write( '                                    <div class=\"row\">\n' );
document.write( '                                        <div class=\"col-12\">\n' );
document.write( '                                            <li><span class=\"icon\"><img src=\"img/icons/wallet.png\" alt=\"\"></span>Downloading Wallet</li>\n' );
document.write( '                                            <li><span class=\"icon\"><img src=\"img/icons/purchasing.png\" alt=\"\"></span>Purchasing Peercoin</li>\n' );
document.write( '                                            <li><span class=\"icon\"><img src=\"img/icons/anvil_black.png\" alt=\"\"></span>Minting Peercoin</li>\n' );
document.write( '                                            <li><span class=\"icon\"><img src=\"img/icons/pickaxe_black.png\" alt=\"\"></span>Mining Peercoin</li>\n' );
document.write( '                                        </div>\n' );
document.write( '                                    </div>\n' );
document.write( '\n' );
document.write( '                                </ul>\n' );
document.write( '                            </li>\n' );
document.write( '                            <li id=\"resources\" class=\"nav-item\">\n' );
document.write( '                                <a class=\"nav-link\" href=\"resources.html\">Resources</a>\n' );
document.write( '                                <ul class=\"submenuitem\">\n' );
document.write( '                                    <li><span class=\"icon\"><img src=\"img/icons/docs.png\" alt=\"\"></span><a href=\"https://docs.peercoin.net/\"><font color=\"black\">Documentation</font></a></li>\n' );
document.write( '                                    <li><span class=\"icon\"><img src=\"img/icons/exchange.png\" alt=\"\"><a href=\"resources.html#exchanges\"><font color=\"black\">Exchanges</font></a></span></li>\n' );
document.write( '                                    <li><span class=\"icon\"><img src=\"img/icons/block.png\" alt=\"\"></span><a href=\"resources.html#blockexplorers\"><font color=\"black\">Block Explorers</font></a></li>\n' );
document.write( '                                    <li><span class=\"icon\"><img src=\"img/icons/whitepaper.png\" alt=\"\"></span><a href=\"resources.html#whitepaper\"><font color=\"black\">Whitepaper</font></a></li>\n' );
document.write( '                                    <li><span class=\"icon\"><img src=\"img/icons/graphics.png\" alt=\"\"></span><a href=\"resources.html#graphics\"><font color=\"black\">Graphics</font></a></li>\n' );
document.write( '                                </ul>\n' );
document.write( '                            </li>\n' );
document.write( '                            <li id=\"projects\" class=\"nav-item\">\n' );
document.write( '                                <a class=\"nav-link\" href=\"#\">Project</a>\n' );
document.write( '                                <ul class=\"submenuitem\">\n' );
document.write( '                                    <li><span class=\"icon\"><img src=\"img/icons/roadmap.png\" alt=\"\"></span><a href=\"roadmap.html\"><font color=\"black\">Roadmap</font></a></li>\n' );
document.write( '                                    <li><span class=\"icon\"><img src=\"img/icons/projects.png\" alt=\"\"></span><a href=\"projects.html\"><font color=\"black\">Projects</font></a></li>\n' );
document.write( '                                    <li><span class=\"icon\"><img src=\"img/icons/blog.png\" alt=\"\"></span><a href=\"https://medium.com/peercoin\"><font color=\"black\">Blog</font></a></li>\n' );
document.write( '                                    <li><span class=\"icon\"><img src=\"img/icons/foundation.png\" alt=\"\"></span><a href=\"foundation.html\"><font color=\"black\">Foundation</font></a></li>\n' );
document.write( '                                    <li><span class=\"icon\"><img src=\"img/icons/contact.png\" alt=\"\"></span><a href=\"contactus.html\"><font color=\"black\">Contact Us</font></a></li>\n' );
document.write( '                                </ul>\n' );
document.write( '                            </li>\n' );
document.write( '                            <li id=\"wallet\" class=\"nav-item\">\n' );
document.write( '                                <a class=\"nav-link\" href=\"wallet.html\">Wallet</a>\n' );
document.write( '                            </li>\n' );
document.write( '                            <li id=\"community\" class=\"nav-item\">\n' );
document.write( '                                <a class=\"nav-link\" href=\"resources.html#communities\">Community</a>\n' );
document.write( '                                <ul class=\"submenuitem\">\n' );
document.write( '                                    <li><span class=\"icon\"><img src=\"img/icons/forum.png\" alt=\"\"></span><a href=\"https://talk.peercoin.net/\"><font color=\"black\">Forum</font></a></li>\n' );
document.write( '                                    <li><span class=\"icon\"><img src=\"img/icons/twitter.png\" alt=\"\"></span><a href=\"https://twitter.com/PeercoinPPC\"><font color=\"black\">Twitter</font></a></li>\n' );
document.write( '                                    <li><span class=\"icon\"><img src=\"img/icons/facebook.png\" alt=\"\"></span><a href=\"https://www.facebook.com/Peercoin/\"><font color=\"black\">Facebook</font></a></li>\n' );
document.write( '                                    <li><span class=\"icon\"><img src=\"img/icons/reddit.png\" alt=\"\"></span><a href=\"https://www.reddit.com/r/peercoin\"><font color=\"black\">Reddit</font></a></li>\n' );
document.write( '                                    <li><span class=\"icon\"><img src=\"img/icons/telegram.png\" alt=\"\"></span><a href=\"https://www.reddit.com/r/peercoin\"><font color=\"black\">Telegram</font></a></li>\n' );
document.write( '                                    <li><span class=\"icon\"><img src=\"img/icons/discord.png\" alt=\"\"></span><a href=\"https://discord.gg/XPxfwtG\"><font color=\"black\">Discord</font></a></li>\n' );
document.write( '                                    <li><span class=\"icon\"><img src=\"img/icons/youtube.png\" alt=\"\"></span><a href=\"https://www.youtube.com/user/PeerCoin\"><font color=\"black\">Youtube</font></a></li>\n' );
document.write( '                                    <li><span class=\"icon\"><img src=\"img/icons/github.png\" alt=\"\"></span><a href=\"https://github.com/peercoin/\"><font color=\"black\">Github</font></a></li>\n' );
document.write( '                                    <li><span class=\"icon\"><img src=\"img/icons/bitcoinchat.png\" alt=\"\"></span><a href=\"https://bitcointalk.org/index.php?topic=101820.0;topicseen\"><font color=\"black\">Bitcoin Talk</font></a></li>\n' );
document.write( '                                </ul>\n' );
document.write( '                            </li>\n' );
document.write( '                        </ul>\n' );
document.write( '                    </div>\n' );
document.write( '                </div>\n' );
document.write( '            </nav>\n' );
document.write( '        </header\n' );
